---
# tasks file for ansible-role-shell-goodies

- debug:
    var: bash_posix_user
    verbosity: 2

- debug:
    var: bash_aliases_file
    verbosity: 2

- debug:
    var: bash_base_aliases
    verbosity: 2

- debug:
    var: bash_aliases_enable
    verbosity: 2

- name: "import base bash aliases"
  become: true
  become_user: "{{ bash_posix_user }}"
  template:
    src: bash_aliases.j2
    dest: "{{ bash_aliases_file }}"
    mode: 0644
  with_items: bash_base_aliases
  when: bash_aliases_enable

- name: "Add to bashrc"
  become: true
  become_user: "{{ bash_posix_user }}"
  lineinfile:
    dest: ~/.bashrc
    regexp: '# User specific aliases and functions'
    insertafter: '# User specific aliases and functions'
    line: 'source {{ bash_aliases_file }}'
    state: present
  when: bash_aliases_enable
